// Generated by https://quicktype.io

export interface DashBoardSummaryResponse {
    numberOfOrders:           number;
    paidOrders:               number;
    numberOfClients:          number;
    numberOfProducts:         number;
    productsWidthNoInventory: number;
    lowInventory:             number;
    notPaidOrders:            number;
}
